export const START_LOADING = 'START_LOADING',
             STOP_LOADING = 'STOP_LOADING',
             REGISTER = 'REGISTER',
             LOGIN = 'LOGIN',
             SELECT_PROFILE = 'SELECT_PROFILE',
             SAVE_PROFILE= 'SAVE_PROFILE',
             DELETE_USER= 'DELETE_USER',
             NOT_AUTHTORIZED= 'NOT_AUTHTORIZED',
             GET_COUNT = 'GET_COUNT'; 
